export const users = [
    {
        "_id": "63bc404d9b151d67ced77f71",
        "isActive": true,
        "balance": "$1,081.25",
        "picture": "http://placehold.it/32x32",
        "age": 27,
        "eyeColor": "green",
        "name": "Tracey Riggs",
        "gender": "female",
        "company": "QUINTITY",
        "email": "traceyriggs@quintity.com",
        "phone": "+1 (925) 558-2427",
        "address": "898 Lawton Street, Churchill, Mississippi, 4650"
    },
    {
        "_id": "63bc404df47dee985a440f4d",
        "isActive": true,
        "balance": "$1,461.96",
        "picture": "http://placehold.it/32x32",
        "age": 35,
        "eyeColor": "green",
        "name": "Staci Knapp",
        "gender": "female",
        "company": "SYNTAC",
        "email": "staciknapp@syntac.com",
        "phone": "+1 (870) 524-3772",
        "address": "604 Richardson Street, Elliott, District Of Columbia, 791"
    },
    {
        "_id": "63bc404d791841ad8a77b1a1",
        "isActive": false,
        "balance": "$3,576.10",
        "picture": "http://placehold.it/32x32",
        "age": 26,
        "eyeColor": "brown",
        "name": "Olive Merritt",
        "gender": "female",
        "company": "OTHERSIDE",
        "email": "olivemerritt@otherside.com",
        "phone": "+1 (865) 543-2529",
        "address": "706 Graham Avenue, Clarksburg, Arkansas, 4199"
    },
    {
        "_id": "63bc404dcf305bd8445e5977",
        "isActive": false,
        "balance": "$2,848.11",
        "picture": "http://placehold.it/32x32",
        "age": 35,
        "eyeColor": "blue",
        "name": "Clemons Bradley",
        "gender": "male",
        "company": "NEUROCELL",
        "email": "clemonsbradley@neurocell.com",
        "phone": "+1 (943) 464-3858",
        "address": "736 Bradford Street, Emison, Montana, 782"
    },
    {
        "_id": "63bc404ddd11f3a485397ac8",
        "isActive": false,
        "balance": "$1,495.66",
        "picture": "http://placehold.it/32x32",
        "age": 34,
        "eyeColor": "blue",
        "name": "Gregory Keller",
        "gender": "male",
        "company": "MEMORA",
        "email": "gregorykeller@memora.com",
        "phone": "+1 (907) 565-3238",
        "address": "999 Bulwer Place, Thermal, Nebraska, 3986"
    },
    {
        "_id": "63bc404d74f767a4959b4abf",
        "isActive": true,
        "balance": "$3,006.84",
        "picture": "http://placehold.it/32x32",
        "age": 29,
        "eyeColor": "green",
        "name": "Mueller Bowers",
        "gender": "male",
        "company": "GADTRON",
        "email": "muellerbowers@gadtron.com",
        "phone": "+1 (870) 499-2198",
        "address": "745 Brevoort Place, Kula, New Jersey, 8116"
    }
]